-- require "plugins"
require "plugins.options"
require "plugins.lazy"
-- require "plugins.edgy_plugins"
require "plugins.alpha"
require "plugins.impatient"
require "plugins.keymaps"
require "plugins.autocommands"
require "plugins.colorscheme"
require "plugins.cmp"
require "plugins.telescope"
require "plugins.gitsigns"
require "plugins.treesitter"
require "plugins.autopairs"
require "plugins.comment"
require "plugins.nvim-tree"
require "plugins.bufferline"
require "plugins.lualine"
require "plugins.toggleterm"
require "plugins.project"
require "plugins.illuminate"
require "plugins.indentline"
require "plugins.lsp"
-- require "plugins.dap"
require "plugins.copilot"
require "plugins.zen"
require "plugins.snippets"
require "plugins.ftdetect"
require "plugins.leap"
