# See https://wiki.hyprland.org/Configuring/Window-Rules/
# Use `hyprctl clients` to find class or title

# Claude Code terminal (scratchpad)
windowrule {
    name = claude-code
    match:class = ^(claude-code)$

    float = on
    size = 1500 1900
    move = 0 130
    border_size = 2
    animation = slideIn left
}
