#!/usr/bin/env bash
# Auto-detect monitors, generate Hyprland config, and update QS scales.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROFILES="$SCRIPT_DIR/display-profiles.json"
MONITORS_CONF="$HOME/.config/hypr/conf/monitors.conf"
SHELL_JSON="$HOME/.config/caelestia/shell.json"

# --- Detect monitors ---
if command -v hyprctl &>/dev/null && hyprctl monitors -j &>/dev/null; then
    monitors_json=$(hyprctl monitors -j)
elif command -v wlr-randr &>/dev/null; then
    monitors_json=$(wlr-randr --json)
else
    echo "display-detect: no monitor backend available" >&2
    exit 1
fi

# --- Parse monitors (highest resolution = primary) ---
primary=$(echo "$monitors_json" | jq -r '
    sort_by(-.width) | .[0] |
    {name, width, height, rate: (.refreshRate // .currentMode.refresh // 60 | floor)}
')
primary_width=$(echo "$primary" | jq -r '.width')

all_monitors=$(echo "$monitors_json" | jq -r '.[] |
    {name, width, height, rate: (.refreshRate // .currentMode.refresh // 60 | floor)}')

# --- Match profile ---
matched_profile=$(jq -r --argjson pw "$primary_width" '
    .profiles[] |
    select(
        ((.match.min_width // 0) <= $pw) and
        ((.match.max_width // 99999) >= $pw)
    ) | .name
' "$PROFILES" | head -1)

if [ -z "$matched_profile" ]; then
    matched_profile="default"
fi

echo "display-detect: primary=${primary_width}px, profile=${matched_profile}"

profile_data=$(jq --arg name "$matched_profile" '.profiles[] | select(.name == $name)' "$PROFILES")
template=$(echo "$profile_data" | jq -r '.monitor_template')

# --- Generate monitors.conf ---
new_conf="# Auto-generated by display-detect.sh — do not edit manually"
while IFS= read -r mon; do
    name=$(echo "$mon" | jq -r '.name')
    width=$(echo "$mon" | jq -r '.width')
    height=$(echo "$mon" | jq -r '.height')
    rate=$(echo "$mon" | jq -r '.rate')

    line=$(echo "$template" |
        sed "s/{name}/$name/g; s/{width}/$width/g; s/{height}/$height/g; s/{rate}/$rate/g")
    new_conf="$new_conf
monitor=$line"
done < <(echo "$monitors_json" | jq -c '.[]  |
    {name, width, height, rate: (.refreshRate // .currentMode.refresh // 60 | floor)}')

# --- Break symlink if present (stow safety) ---
if [ -L "$MONITORS_CONF" ]; then
    rm "$MONITORS_CONF"
fi

# --- Skip if monitors.conf unchanged ---
old_hash=""
if [ -f "$MONITORS_CONF" ]; then
    old_hash=$(md5sum "$MONITORS_CONF" | cut -d' ' -f1)
fi
new_hash=$(echo "$new_conf" | md5sum | cut -d' ' -f1)

monitors_changed=false
if [ "$old_hash" != "$new_hash" ]; then
    echo "$new_conf" > "$MONITORS_CONF"
    monitors_changed=true
    echo "display-detect: updated monitors.conf"
fi

# --- Update shell.json scales ---
qs_scales=$(echo "$profile_data" | jq '.qs_scales')
rounding=$(echo "$qs_scales" | jq -r '.rounding')
spacing=$(echo "$qs_scales" | jq -r '.spacing')
padding=$(echo "$qs_scales" | jq -r '.padding')
font_size=$(echo "$qs_scales" | jq -r '.font_size')

if [ -f "$SHELL_JSON" ]; then
    new_shell=$(jq \
        --argjson r "$rounding" \
        --argjson s "$spacing" \
        --argjson p "$padding" \
        --argjson f "$font_size" \
        '.appearance.rounding.scale = $r |
         .appearance.spacing.scale = $s |
         .appearance.padding.scale = $p |
         .appearance.font.size.scale = $f' \
        "$SHELL_JSON")

    old_shell_hash=$(md5sum "$SHELL_JSON" | cut -d' ' -f1)
    new_shell_hash=$(echo "$new_shell" | md5sum | cut -d' ' -f1)

    if [ "$old_shell_hash" != "$new_shell_hash" ]; then
        echo "$new_shell" > "$SHELL_JSON"
        echo "display-detect: updated shell.json scales (profile: $matched_profile)"
    fi
fi

# --- Reload Hyprland if monitors changed ---
if [ "$monitors_changed" = true ] && command -v hyprctl &>/dev/null; then
    hyprctl reload
    echo "display-detect: reloaded hyprland"
fi
