[colors]

[colors.normal]
black   = "#72696a"
red = "#fd6883"
green = "#adda78"
yellow = "#f9cc6c"
blue = "#f38d70"
magenta = "#a8a9eb"
cyan = "#85dacc"
white = "#e6d9db"

[colors.bright]
black = "#948a8b"
red     = "#ff8297"
green   = "#c8e292"
yellow  = "#fcd675"
blue    = "#f8a788"
magenta = "#bebffd"
cyan    = "#9bf1e1"
white   = "#f1e5e7"

[colors.cursor]
cursor = '#c3b7b8'
text = '#2c2525'

[colors.primary]
background = '#2c2525'
foreground = '#e6d9db'

[colors.selection]
background = '#403e41'
text = '#e6d9db'
