# See https://wiki.hyprland.org/Configuring/Monitors/
source = ~/.config/hypr/conf/monitors.conf

# See https://wiki.hyprland.org/Configuring/Keywords/ for more
source = ~/.config/hypr/conf/startup.conf
source = ~/.config/hypr/conf/windowrules.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/general.conf
