require("plugins.lazy")
require("plugins.keymaps")
require("plugins.config.bufferline")
require("plugins.config.neotree")
require("plugins.config.lualine")
require("plugins.config.illuminate")
require("plugins.lsp")
require("plugins.config.cmp")
