# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 200
format = "[$directory$git_branch$git_status]($style)$character"

[character]
error_symbol = "[✗](bold cyan)"
success_symbol = "[❯](bold cyan)"

[directory]
truncation_length = 2
truncation_symbol = "…/"
repo_root_style = "bold cyan"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[git_branch]
format = "[$branch]($style) "
style = "italic cyan"

[git_status]
format     = '[$all_status]($style)'
style      = "cyan"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

[package]
disabled = true

[aws]
style = "bold green"
format = '| [$symbol$region]($style) '

[azure]
disabled = false
format = "| [$symbol($subscription)]($style) "
symbol = " "
style = "blue bold"

[kubernetes]
disabled = true
format = '[⛵$context on $namespace](purple) '

[container]
style = "bold yellow dimmed"
format ="[$symbol devtainer]($style) "
symbol = "⬢"
disabled = false

[python]
format = '[$symbol$version]($style) '
python_binary = ['./venv/bin/python', 'python', 'python3', 'python2']

[terraform]
symbol = "󱁢 "
