#!/usr/bin/env bash

 brave-browser-beta&
 sxhkd&
# export fcitx5 environment variables
#export GTK_IM_MODULE=fcitx5
#export QT_IM_MODULE=fcitx5
#export XMODIFIERS="@im=fcitx5"
#export GLFW_IM_MODULE=ibus
# sxhkd&
# fcitx5 &
# firefox&

 if [ -x "$(command -v feh)" ]; then
    feh --bg-fill "$HOME/Pictures/astronoutspace.jpg"
fi
